### ISSUE TITLE
Create Tests

### ISSUE THREAD

**Issue by AlokBansal8** [AlokBansal8/RxFirebase#1]
Create Test classes

Problem with creating test is that I don't yet know how to test Firebase.

**Comment by AlokBansal8** [comment]
@urish can you help?

**Comment by urish** [comment]
Sorry, but I have no experience with setting up firebase tests in Android. You may try checking out these issues for people who may be able to help:
- https://github.com/urish/firebase-server/issues/59
- https://github.com/urish/firebase-server/issues/9

Good luck with your project!

**Comment by AlokBansal8** [comment]
Thanks @urish.
@diego1686, @azell can you help?
